services:
  aria2-rpc:
    build:
      context: .
      dockerfile: Dockerfile.aria2
    container_name: poc-aria2-backend
    ports:
      - "6800:6800"
    volumes:
      - ./Descargas:/downloads
      - ./aria2_config:/config
    restart: unless-stopped