services:
  aria2-rpc:
    image: alpine:edge
    container_name: poc-aria2-backend
    cap_add:
      - NET_ADMIN  
    environment:
      - PROXY_IP=${PROXY_IP:-127.0.0.1}
      - PROXY_PORT=${PROXY_PORT:-1080}
    command:
      - /bin/sh
      - -c
      - |
        echo "[*] Instalando dependencias (Aria2, Privoxy, dnsmasq, curl)..."
        apk update && apk add --no-cache aria2 privoxy iptables dnsmasq curl

        echo "[*] Configurando Fake-DNS (Para engañar a Aria2 y evitar fugas)..."
        echo "address=/#/10.10.10.10" > /etc/dnsmasq.conf
        dnsmasq --user=root

        echo "[*] Configurando Privoxy (Resolución DNS remota - SOCKS5h)..."
        # CAMBIO 1: Ahora Privoxy escucha en 0.0.0.0 para aceptar órdenes de Python
        echo "listen-address 0.0.0.0:8118" > /etc/privoxy/config
        echo "accept-intercepted-requests 0" >> /etc/privoxy/config
        echo "forward-socks5t / $${PROXY_IP}:$${PROXY_PORT} ." >> /etc/privoxy/config
        privoxy /etc/privoxy/config

        echo "[*] Aplicando Kill-Switch (Zero Trust) en iptables..."
        iptables -F OUTPUT
        iptables -A OUTPUT -o lo -j ACCEPT
        iptables -A OUTPUT -d 10.0.0.0/8 -j ACCEPT
        iptables -A OUTPUT -d 172.16.0.0/12 -j ACCEPT
        iptables -A OUTPUT -d 192.168.0.0/16 -j ACCEPT
        iptables -A OUTPUT -d $${PROXY_IP} -p tcp --dport $${PROXY_PORT} -j ACCEPT
        iptables -A OUTPUT -j REJECT

        echo "[*] Arrancando motor de descargas..."
        exec aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --rpc-listen-port=6800 --dir=/downloads --max-connection-per-server=4 --split=4 --min-split-size=1M --all-proxy=http://127.0.0.1:8118 --async-dns-server=127.0.0.1
    ports:
      - "6800:6800"
      - "8118:8118"
    volumes:
      - ./Descargas:/downloads
      - ./aria2_config:/config
    restart: unless-stopped