name: Security Quality Gate

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  snyk-python:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Crear requirements.txt temporal
        run: |
          echo "yt-dlp" > requirements.txt
          echo "requests" >> requirements.txt

      - name: Escanear dependencias Python con Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk-code.sarif

      - name: Subir reporte SARIF de Código a GitHub
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: snyk-code.sarif
          category: snyk-python

  snyk-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Construir imagen Docker de Aria2
        run: docker build -t aria2-backend:local -f Dockerfile.aria2 .

      - name: Escanear Docker con Snyk
        id: snyk_docker_scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: aria2-backend:local
          args: --file=Dockerfile.aria2 --severity-threshold=high --sarif-file-output=snyk-docker.sarif

      - name: Subir reporte SARIF de Docker a GitHub
        uses: github/codeql-action/upload-sarif@v4
        if: steps.snyk_docker_scan.outcome == 'failure' 
        with:
          sarif_file: snyk-docker.sarif
          category: snyk-docker

      - name: Verificar estado del escaneo
        if: steps.snyk_docker_scan.outcome == 'failure'
        run: exit 1